src/charm.py, tests/test_charm.py
Enabling HTTPS takes some doing:
https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html
This was set to True in #12 when it really should've been False
=> Disable secure flag as default

.github/workflows/publish.yaml
Previous commit erroneously missed updating the image included in the published bundle
=> fix: make publish.yaml dynamically set container image

README.md, config.yaml, src/charm.py, tests/unit/test_charm.py
Changes:
- Added gateway storage endpoint to support the private endpoints in Azure and AWS
- Renamed the gateway fields to keep the same naming convention as access and secret key. ("_" to "-")
Tests:
- same as in https://github.com/canonical/minio-operator/pull/27
- additional test of checking the gateway mode with public and private endpoints explicitly put into the configuration
=> Feature/gateway storage endpoint - support for private endpoints for Azure and AWS

src/charm.py, tests/unit/test_charm.py
This change will store the Access and Secret key environment variables in Kubernetes secrets therefore not exposing them as plain text.
Fixes #30
=> Handle Acces and Secret Keys with Secrets

README.md, config.yaml, src/charm.py, tests/integration/test_charm.py, tests/unit/test_charm.py
**Added**:
- minio console port to configuration with the default value of 9001
- minio console port to minio args in container 
- unit tests (or adjusted) to check port value
- README - minio console section
**Tests** - server and gateway mode deployed using default and then changing the port value.
=> Minio Console added to the charm configuration

src/charm.py, test-requirements.txt, tests/integration/test_charm.py
Refactors existing integration tests to make it easier to reuse the logic for future tests.  This should not affect the function of the tests
=> Refactor integration tests

src/charm.py, tests/integration/test_charm.py, tests/unit/test_charm.py
Implements handling of changes to Minio's credentials.  Previously, `juju config minio access-key something-new` would not trigger a restart of the Minio workload, thus not actually change the credentials (unless the pod was later deleted).  This PR implements logic to automate this, as well as tests to support it.
This should be reviewed after reviewing #49 as it builds on fixes from that PR.
=> fix: credential refresh on config change

.github/workflows/integrate.yaml, .github/workflows/on_pull_request.yaml, .github/workflows/on_push.yaml, .github/workflows/publish.yaml, .github/workflows/release.yaml, lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py
Charming actions updated according to the ones agreed on template-operator charm.
The aim was to:
- add release charm action
- have two publish actions for `on: push` and `on: pull_request`:
- on pull_request, publish to branch no matter if tests passed (tests and publish should run simultaneously)
- on push, publish to latest/edge only if tests passed
- avoid re-running the tests on pull_request
- use reusable workflows in order to avoid duplication of code.
Note: this is a single-charm repo with one resource.
=> Add charming actions

.gitignore, src/charm.py, tests/unit/test_charm.py
This PR standardizes handling the status when the unit is not leader and adds `leader-elected` to observed events.
=> Observe leader elected

src/charm.py
The securityContext on each charm is allowing containers to run
in privileged mode, which is not always desirable as we would be
granting unrestricted access to the OS. This securityContext was
also setting up runAsNonRoot and readOnlyRootFilesystem to false,
which are not needed.
fixes: canonical/minio-operator#69
=> fix: removes securityContext from podspec

metadata.yaml
https://github.com/canonical/minio-operator/issues/78
Summary of changes:
- Removed minimum size requirements from metadata.yaml
=> fix: set minimum size requirements to 1G (default)

.github/workflows/integrate.yaml
to be consistent in all of our repos, use `charmed-kubernetes/actions-operator@main` in `Setup operator environment` step
=> fix: use charmed kubernetes actions operator

metadata.yaml
This reverts commit 981ad49ad356efffc454f8fe8abb69d5752d78b9.
=> Revert "fix: set minimum size requirement to 1G"

metadata.yaml
This reverts commit 981ad49ad356efffc454f8fe8abb69d5752d78b9, which solved #78.   We have reverted this because it causes trouble with the upgrade path of the charm. juju will not let you refresh a charm if the storage minimum size has changed between revisions. Because of this, we'll leave the larger minimum storage size in order to preserve the upgrade path
=> Revert "fix: set minimum size requirement to 1G", set minimum to 10G(#117)

tools/get-images.sh
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup. Script is specific for track/ckf-1.7 branch to capture all images for that branch. Branch is handled in kubeflow-ci and bundle automation using bundle file.
Summary of changes:
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.
=> feat: updated get images script without branch checkout for track/ckf-1.7

src/charm.py, tests/unit/test_charm.py
The upstream pipelines project hardcodes the name of the object storage service to minio-service. The current implementation sets the service to just minio, which collides with what pipelines expect. This PR ensures the Service is created with the expected name and ports.
To test this change, you can build and deploy the charm and look for the Service `minio-service`. It should have the following:
* name should be `minio-service` 
* there must be a port with name `minio` and targetPort:9000
* there must be a port with name `console` and targetPort:9001
* the selector must be `app.kubernetes.io/name: minio`
These are the logs we are trying to avoid with the changes in this PR:
```
failed to execute component: failed to upload output artifact "output_dataset_one" to remote storage URI …
```
=> fix: explicitly apply minio-service with name

src/charm.py, tests/unit/test_charm.py
This reverts commit b99aad877107c8023b981fe06e945a51f2622362 as described in #153.  This fix is instead being moved to the kfp-api charm of [kfp-operators](https://github.com/canonical/kfp-operators).
=> Revert "fix: explicitly apply minio-service with name (#151)"

src/charm.py, tests/integration/test_charm.py
This variable allows public access without authentication for prometheus metrics.
Part of canonical/bundle-kubeflow#564
Please refer to the steps to reproduce in [this comment](https://github.com/canonical/bundle-kubeflow/issues/564#issuecomment-1925538870), just deploying this app. After deploying this app and cos-lite, relations and dependencies, and waiting a couple minutes (10 min) none of the alerts should fire (for this app only).
=> fix: set prometheus authentication variable

src/charm.py, tests/integration/test_charm.py
* fix: set prometheus authentication variable
This variable allows public access without authentication for prometheus metrics.
Part of canonical/bundle-kubeflow#564
* tests: add an assertion for checking unit is available
The test_prometheus_grafana_integration test case was doing queries to prometheus and checking the request returned successfully and that the application name and model was listed correctly. To make this test case more accurately, we can add an assertion that also checks that the unit is available, this way we avoid issues like the one described in canonical/bundle-kubeflow#564.
Part of canonical/bundle-kubeflow#564
=> fix: set prometheus authentication variable (#157)

src/grafana_dashboards/minio-overview_rev13.json.tmpl
This PR is part of https://github.com/canonical/bundle-kubeflow/issues/856.
It fixes the dashboard by:
* Removing `job=scrape_jobs` label from dashboard fields
* Removing panels using metrics that are not provided by the minio workload.
* Reorder panels for filling gaps created by removed panels.
On top of that, it adds a `ckf` tag to the dashboard.
Ref canonical/bundle-kubeflow#856
=> fix: Fix grafana dashboard

src/grafana_dashboards/minio-overview_rev13.json.tmpl
Backport the following fix for the dashboard:
* Remove `job=scrape_jobs` label from dashboard fields
* Remove panels using metrics that are not provided by the minio workload.
* Reorder panels for filling gaps created by removed panels.
On top of that, it adds a `ckf` tag to the dashboard.
Part of canonical/bundle-kubeflow#856
Ref canonical/bundle-kubeflow#834
=> backport(fix): Fix grafana dashboard from #159

.github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
=> ci(upload-charm): use charmcraft from latest/candidate in track/ckf-1.9

.github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
=> ci(upload-charm): use charmcraft from latest/candidate in track/ckf-1.8

config.yaml, src/charm.py
Closes https://github.com/canonical/minio-operator/issues/137.
This PR adds an additional check in the charm.py file to ensure that the `secret-key` is at least 8 characters long. If it isn't, the charm's status changes to blocked with an appropriate message.
The minimum size of 8 characters seems to be hard-coded in [this line](https://github.com/minio/minio/blob/4e67a4027e3c9ba7f294bd71a9000b03c5efad7e/internal/auth/credentials.go#L45).
=> Set status to Blocked when secret-key is shorter than 8 characters long

config.yaml, src/charm.py
Ensure that the secret-key is at least 8 characters long
Fix #137
=> backport(fix): block when secret-key is too short from #178

requirements-fmt.txt, requirements-integration.txt, requirements-lint.txt, requirements-unit.in, requirements-unit.txt, requirements.txt, tests/unit/test_charm.py, tox.ini
* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
* Remove unused pytest-lazy-fixture package
* Remove mocking of private ops class according to canonical/operator#1369 and canonical/seldon-core-operator#268
Ref canonical/bundle-kubeflow#1177
Ref canonical/bundle-kubeflow#1185
=> chore: update python dependencies + pin pip

metadata.yaml
Integrating this rock image guarantees that the minio workload will have access to the mounted storage to start the service correctly.
Part of canonical/charmed-kubeflow-uats#163
=> fix: integrate minio:ckf-1.10-b40ac43 to fix permission issue

.github/workflows/integrate.yaml, .github/workflows/publish.yaml, .github/workflows/release.yaml, metadata.yaml, tests/integration/test_charm.py
Closes #206 
* update GH runners from 20.04 to 24.04
* use setup-python action to setup python 3.8
* edit the integration tests to use `kubectl` instead of `microk8s kubectl` so that elevated permissions are not needed
* removes `sg` no longer needed based on the previous point
=> chore: migrate GH runners to ubuntu 24.04

charmcraft.yaml, constraints.txt
Due to python/importlib_metadata#516, we need to set up constaints to the `setuptools-scm` to avoid install loops for these charms dependencies, as recommended by the charmcraft team (see https://github.com/canonical/charmcraft/issues/2259#issuecomment-2842766428).
=> fix: setuptools

src/prometheus_alert_rules/KubeflowMinioServices.rules
Closes: https://github.com/canonical/minio-operator/issues/216
Alert rules based on: https://github.com/canonical/minio-operator/issues/212
After trying to deploy proposed rules from the exploration task, I found out that the rule `Alert for High Time to First Byte (TTFB) (over 500ms)` is not useful as it is based on metric `minio_s3_time_ttfb_seconds_distribution` which is a hystogram based metric which is not yealding good results on cold starts when there is not too many records.
I have tested manuallu by:
- running integration tests
- deploying cos lite on top of that 
- checking the prometheus dashboard for alert rules
=> feat: integrate minio alert rules

.gitignore, src/prometheus_alert_rules/KubeflowMinioServices.rules
Follpw-up of https://github.com/canonical/minio-operator/pull/223
To update the Alert to better reflect Failure Mode that expose the underlying issue, like FDs and space running out.
https://github.com/canonical/minio-operator/issues/212#issuecomment-2862916743
=> feat: update the alert rules for failure modes

requirements-integration.in, requirements-integration.txt
Cherry pick of #241 to `track/ckf-1.10`, currently the CI is [broken](https://github.com/canonical/minio-operator/actions/runs/17240091470) due to deploying from the deprecated COS channel. See https://github.com/canonical/charmed-kubeflow-chisme/issues/155 for details.
=> Update chisme in requirements (#241)

src/charm.py, tests/unit/test_charm.py
Closes #253 
For details on the fix and root cause, see #253
Tested in https://github.com/canonical/charmed-kubeflow-solutions/pull/62, specifically https://github.com/canonical/charmed-kubeflow-solutions/commit/c212429a0fafeef041ae9d3e33b9224904ad8cb9
* adds `update_status` to the charm's observed events
* on failure to find the oci image, sets the status to `waiting` rather than `blocked` due to no human intervention being expected
=> fix: handle missing oci-image case
